name: Stack Library

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install the Requirments
        run: |
          pip install -r requirements.txt
          pip install -r requirements_test.txt
      - name: Pre-commit
        run: |
          pre-commit run --all-files
      - name: Test
        run: |
          pytest test/test_stack.py
      - name: Prepare package for release
        if: github.ref == 'refs/heads/master'
        run: |
          python3 setup.py sdist
          cp ./dist/*.tar.gz ${RUNNER_TEMP}/stack.tar.gz
